# Generated by Django 5.0.3 on 2024-06-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_company_potentialuser_remove_document_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file_name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="documentmeta",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
    ]
