# Generated by Django 5.0.3 on 2024-06-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_document_file_name_documentmeta_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentmeta",
            name="metadata",
            field=models.TextField(),
        ),
    ]
