# Generated by Django 5.0.3 on 2024-06-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_documentmeta_metadata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentmeta",
            name="metadata",
        ),
        migrations.AddField(
            model_name="documentmeta",
            name="creation_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentmeta",
            name="file_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="documentmeta",
            name="is_directory",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="documentmeta",
            name="last_accessed_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentmeta",
            name="last_modified_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentmeta",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="documentmeta",
            name="permissions",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="documentmeta",
            name="size_bytes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
