# Generated by Django 5.0.3 on 2024-06-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_documentmeta_metadata_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentmeta",
            name="permissions",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
