name: Run Tests

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs to run in the workflow
jobs:
  test:
    # The environment to run the job in
    runs-on: ubuntu-latest

    # Steps to execute in the job
    steps:
      # Check out the repository
      - name: Check out repository code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.5  # Specify the Python version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the tests
      - name: Run tests
        run: |
          pytest
