name: Run Tests and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Check out repository code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.5

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests
      - name: Run tests
        run: pytest
        continue-on-error: false  # Ensure tests stop the deployment if they fail

      # Deploy only if on push to main (not pull request)
      - name: Deploy to EC2
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{ secrets.EC2_HOST }}
            USER_NAME: ${{ secrets.EC2_USER }}
        run: |
            # Create the private key and set proper permissions
            echo "$PRIVATE_KEY" > private_key && chmod 600 private_key

            # SSH into EC2 and run the deploy script
            ssh -o StrictHostKeyChecking=no -i private_key "${USER_NAME}@${HOSTNAME}" "
            cd /home/ubuntu/aleph_backend/aleph && ./deploy.sh
            "
