name: Run Tests and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Check out repository code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.5

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests
      - name: Run tests
        run: pytest
        continue-on-error: false  # Ensure tests stop the deployment if they fail

      # Debug step to check if secrets are being passed correctly
      - name: Debug Environment Variables
        run: |
          echo "EC2_USER=$EC2_USER"
          echo "EC2_HOST=$EC2_HOST"
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}

      # Create .ssh directory and add EC2 host to known_hosts
      - name: Add EC2 to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan $EC2_HOST >> ~/.ssh/known_hosts
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}

      # Deploy to EC2
      - name: Deploy to EC2
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          # Save the private key, removing potential carriage return characters
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > id_rsa
          chmod 600 id_rsa

          # Test SSH connection to verify key is valid
          ssh -i id_rsa -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "echo SSH connection successful"

          # Rsync and deploy
          rsync -avz --exclude='.git' -e "ssh -i id_rsa" ./ $EC2_USER@$EC2_HOST:/home/ubuntu/aleph_backend/aleph
          ssh -i id_rsa $EC2_USER@$EC2_HOST "cd /home/ubuntu/aleph_backend/aleph && ./deploy.sh"
